# general settings
name: 051_RRDBNet_PSNR_x4_TFSR_ft_wCanny_MaskedCannyperceptual
model_type: SRModel
scale: 4
num_gpu: auto  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: RealCE
    type: PairedImageDatasetRealCEwRECwLabelMapwCannyv2
    dataroot_gt: /data0_ssd2t/majianqi/RealCE
    dataroot_lq: /data0_ssd2t/majianqi/RealCE
    meta_info_file: None
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 256
    use_hflip: false
    use_rot: false

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 100
    prefetch_mode: ~
    synthetic_degr: true

  val:
    name: RealCE
    type: PairedImageDatasetRealCEwRECwLabelMapwCannyv2
    dataroot_gt: /data0_ssd2t/majianqi/RealCE
    dataroot_lq: /data0_ssd2t/majianqi/RealCE
    io_backend:
      type: disk

# network structures
network_g:
  type: RRDBNet
  num_in_ch: 4
  num_out_ch: 4
  num_feat: 64
  num_block: 23
  num_grow_ch: 32

# path
path:
  pretrain_network_g: ~ #experiments/051_RRDBNet_PSNR_x4_TFSR_pretrain/models/net_g_100000.pth
  strict_load_g: false
  resume_state: ~
  experiments_root: /data1_ssd4t/majianqi/experiments/051_RRDBNet_PSNR_x4_RealCE_ft_wCanny_Cannyperceptual

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  #scheduler:
  #  type: CosineAnnealingRestartLR
  #  periods: [100000, 120000, 400000, 400000]
  #  restart_weights: [1, 1, 1, 1]
  #  eta_min: !!float 1e-7

  scheduler:
    type: MultiStepLR
    milestones: [ 100000, 150000, 175000, 200000 ]
    gamma: 0.5

  total_iter: 200000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: MaskedL1Loss
    loss_weight: 1.0
    reduction: mean

  perceptual_opt:
    type: CannyPerceptualLoss
    layer_weights:
      'conv5_4': 0.0004  # before relu
      'conv4_4': 0.0004
      'conv3_4': 0.0008
    vgg_type: vgg19
    use_input_norm: true
    range_norm: false
    perceptual_weight: 1.0
    style_weight: 0.0
    criterion: l1

# validation settings
val:
  val_freq: !!float 5e3
  save_img: true

  metrics:
    psnr_torch: # metric name, can be arbitrary
      type: calculate_psnr_torch
      crop_border: 2
      test_y_channel: false
    ssim_torch:
      type: calculate_ssim_torch
      crop_border: 2
      test_y_channel: false
    mask_ssim:
      type: calculate_region_ssim
      crop_border: 2
      test_y_channel: false
    mask_psnr:
      type: calculate_region_psnr
      crop_border: 2
      test_y_channel: false
    lpips:
      type: calculate_lpips
      crop_border: 2
      test_y_channel: false
    recognition:
      type: calculate_recognition_case_insensitive_langdivide
      crop_border: 2
      test_y_channel: false
    ned:
      type: calculate_recognition_case_insensitive_langdivide
      crop_border: 2
      test_y_channel: false
    recognition_divide:
      type: calculate_recognition_case_insensitive_langdivide
      crop_border: 2
      test_y_channel: false
    recognition_CHN:
      type: calculate_recognition_case_insensitive_langdivide
      crop_border: 2
      test_y_channel: false
    recognition_ENG:
      type: calculate_recognition_case_insensitive_langdivide
      crop_border: 2
      test_y_channel: false
    ned_CHN:
      type: calculate_recognition_case_insensitive_langdivide
      crop_border: 2
      test_y_channel: false
    ned_ENG:
      type: calculate_recognition_case_insensitive_langdivide
      crop_border: 2
      test_y_channel: false


# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
