# general settings
name: train_RRDB_SRx2_scratch_v2
model_type: SRModel
scale: 4
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: TFSR
    type: PairedImageDatasetTFSRwREC
    dataroot_gt: /data0_ssd2t/majianqi/TextZoom
    dataroot_lq: /data0_ssd2t/majianqi/TextZoom
    # (for lmdb)
    # dataroot_gt: datasets/DIV2K/DIV2K_train_HR_sub.lmdb
    # dataroot_lq: datasets/DIV2K/DIV2K_train_LR_bicubic_X4_sub.lmdb
    filename_tmpl: '{}'
    io_backend:
      type: disk
      # (for lmdb)
      # type: lmdb

    gt_size: 128
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: TFSR
    type: PairedImageDatasetTFSRwREC
    dataroot_gt: /data0_ssd2t/majianqi/TFSR
    dataroot_lq: /data0_ssd2t/majianqi/TFSR
    io_backend:
      type: disk

# network structures
network_g:
  type: RRDBNet
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  num_block: 23
  num_grow_ch: 32
  scale: 4
# path
path:
  pretrain_network_g: ~
  strict_load_g: false
  resume_state: ~
  experiments_root: /data1_ssd4t/majianqi/experiments/train_RRDB_SRx2_scratch_v2

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [100000, 400000, 400000, 400000]
    restart_weights: [1, 1, 1, 1]
    eta_min: !!float 1e-7

  total_iter: 100000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: MaskedL1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 1e4
  save_img: true

  metrics:
    psnr_torch: # metric name, can be arbitrary
      type: calculate_psnr_torch
      crop_border: 2
      test_y_channel: false
    ssim_torch:
      type: calculate_ssim_torch
      crop_border: 2
      test_y_channel: false
    mask_ssim:
      type: calculate_region_ssim
      crop_border: 2
      test_y_channel: false
    mask_psnr:
      type: calculate_region_psnr
      crop_border: 2
      test_y_channel: false
    lpips:
      type: calculate_lpips
      crop_border: 2
      test_y_channel: false
    recognition:
      type: calculate_recognition
      crop_border: 2
      test_y_channel: false
    ned:
      type: calculate_recognition
      crop_border: 2
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
