# general settings
name: train_ELAN_SRx2_scratch_ln_wcanny
model_type: ELANModel
scale: 2
num_gpu: auto
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: TFSR
    type: PairedImageDatasetTFSRwRECwLabelMapwCannyv2
    dataroot_gt: /data0_ssd2t/majianqi/TFSR
    dataroot_lq: /data0_ssd2t/majianqi/TFSR
    meta_info_file: None
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 128
    use_hflip: false
    use_rot: false

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: TFSR
    type: PairedImageDatasetTFSRwRECwLabelMapwCannyv2
    dataroot_gt: /data0_ssd2t/majianqi/TFSR
    dataroot_lq: /data0_ssd2t/majianqi/TFSR
    io_backend:
      type: disk

# network structures
network_g:
  type: ELAN
  scale: 2
  colors_in: 4
  colors_out: 4
  window_sizes: [8, 16, 32]
  m_elan: 36
  c_elan: 180
  n_share: 0
  r_expand: 2
  rgb_range: 1.

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~
  experiments_root: /data1_ssd4t/majianqi/experiments/train_ELAN_SRx2_scratch_ln_wcanny

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [100000, 100000, 200000, 475000]
    gamma: 0.5

  total_iter: 150000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: MaskedL1Loss
    loss_weight: 1.0
    reduction: mean

  #ssim_opt:
  #  type: SSIMLoss
  #  loss_weight: 0.1
  #  reduction: mean

  #gpt_opt:
  #type: GradientPriorLoss
  #loss_weight: 1e-3
  #reduction: mean

  # aux_loss: false

# validation settings
val:
  val_freq: !!float 1e4
  save_img: true

  metrics:
    psnr_torch: # metric name, can be arbitrary
      type: calculate_psnr_torch
      crop_border: 2
      test_y_channel: false
    ssim_torch:
      type: calculate_ssim_torch
      crop_border: 2
      test_y_channel: false
    mask_ssim:
      type: calculate_region_ssim
      crop_border: 2
      test_y_channel: false
    mask_psnr:
      type: calculate_region_psnr
      crop_border: 2
      test_y_channel: false
    lpips:
      type: calculate_lpips
      crop_border: 2
      test_y_channel: false
    recognition:
      type: calculate_recognition
      crop_border: 2
      test_y_channel: false
    ned:
      type: calculate_recognition
      crop_border: 2
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
