# TODO
# general settings
name: 201_RCANx4_scratch_TFSR_ft_wCanny_CannyPerceptual
model_type: SRModel
scale: 4
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    name: TFSR
    type: PairedImageDatasetTFSRwRECwLabelMapwCannyv2
    dataroot_gt: /data0_ssd2t/majianqi/TFSR
    dataroot_lq: /data0_ssd2t/majianqi/TFSR
    meta_info_file: None
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 256
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val: # the 1st test dataset
    name: 13mm
    type: PairedImageDatasetTFSRwRECwLabelMapwCannyv2
    dataroot_gt: /data0_ssd2t/majianqi/TFSR/
    dataroot_lq: /data0_ssd2t/majianqi/TFSR/
    io_backend:
      type: disk

# network structures
network_g:
  type: RCAN
  num_in_ch: 4
  num_out_ch: 4
  num_feat: 64
  num_group: 10
  num_block: 20
  squeeze_factor: 16
  upscale: 4
  res_scale: 1
  img_range: 1.
  rgb_mean: [0.4488, 0.4371, 0.4040, 0]

# path
path:
  pretrain_network_g: /data1_ssd4t/majianqi/experiments/201_RCANx4_scratch_TFSR_pretrain_archived_20221030_151326/models/net_g_100000.pth
  strict_load_g: false
  resume_state: ~
  experiments_root: /data1_ssd4t/majianqi/experiments/201_RCANx4_scratch_TFSR_ft_wCanny_CannyPerceptual

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [100000]
    gamma: 0.5

  total_iter: 100000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: MaskedL1Loss
    loss_weight: 1.0
    reduction: mean

  perceptual_opt:
    type: CannyPerceptualLoss
    layer_weights:
      'conv5_4': 0.0004  # before relu
      'conv4_4': 0.0004
      'conv3_4': 0.0008
    vgg_type: vgg19
    use_input_norm: true
    range_norm: false
    perceptual_weight: 1.0
    style_weight: 0.0
    criterion: l1

# validation settings
val:
  val_freq: !!float 1e4
  save_img: false

  metrics:
    psnr_torch: # metric name, can be arbitrary
      type: calculate_psnr_torch
      crop_border: 2
      test_y_channel: false
    ssim_torch:
      type: calculate_ssim_torch
      crop_border: 2
      test_y_channel: false
    mask_ssim:
      type: calculate_region_ssim
      crop_border: 2
      test_y_channel: false
    mask_psnr:
      type: calculate_region_psnr
      crop_border: 2
      test_y_channel: false
    lpips:
      type: calculate_lpips
      crop_border: 2
      test_y_channel: false
    recognition:
      type: calculate_recognition
      crop_border: 2
      test_y_channel: false
    ned:
      type: calculate_recognition
      crop_border: 2
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
