# general settings
name: pretrain_SwinIR_SRx2_scratch_P64W8_TFSR_500k_B4G8_codebook_real_1024_gpt_loss
model_type: SwinIRModel
scale: 2
num_gpu: auto
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: Synthetic
    type: PairedImageDatasetSynthetic
    dataroot_gt: /data0_ssd2t/majianqi/LSVT
    dataroot_lq: None
    meta_info_file: None
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 128
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: TFSR
    type: PairedImageDatasetTFSR
    dataroot_gt: /data0_ssd2t/majianqi/TFSR
    dataroot_lq: /data0_ssd2t/majianqi/TFSR
    io_backend:
      type: disk

# network structures
network_g:
  type: SwinIR
  upscale: 2
  in_chans: 3
  img_size: 64
  window_size: 8
  img_range: 1.
  depths: [4, 4, 4, 4, 4, 4]
  embed_dim: 180
  num_heads: [4, 4, 4, 4, 4, 4]
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [250000, 400000, 450000, 475000]
    gamma: 0.5

  total_iter: 5000000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean


  aux_loss: false

# validation settings
val:
  val_freq: !!float 1e5
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 2
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
