# general settings
name: train_TPSwinIR_SRx4_withTrainsetCorrected_originalSet_wCanny_ft
model_type: TP_SwinIRModel
scale: 4
num_gpu: auto
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: TFSR
    type: PairedImageDatasetTFSRwRECwLabelMapwCanny
    dataroot_gt: /data0_ssd2t/majianqi/TFSR #["/data0_ssd2t/majianqi/TFSR", "/data0_ssd2t/majianqi/ReCTS", "/data0_ssd2t/majianqi/LSVT"] #
    dataroot_lq: /data0_ssd2t/majianqi/TFSR
    meta_info_file: None
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 256
    use_hflip: false
    use_rot: false

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val: # the 1st test dataset
    name: 13mm
    type: PairedImageDatasetTFSRwRECwLabelMapwCanny
    dataroot_gt: /data0_ssd2t/majianqi/TFSR/
    dataroot_lq: /data0_ssd2t/majianqi/TFSR/
    io_backend:
      type: disk

# network structures
network_g:
  type: TP_SwinIR
  upscale: 4
  in_chans: 4
  img_size: 64
  window_size: 8
  img_range: 1.
  depths: [6, 6, 6, 6, 6, 6]
  embed_dim: 180
  num_heads: [6, 6, 6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'

# path
path:
  pretrain_network_g: experiments/train_TPSwinIR_SRx4_withTrainsetCorrected_originalSet_wCanny_pretrain/models/net_g_100000.pth
  strict_load_g: false
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [40000, 60000]
    gamma: 0.5

  total_iter: 100000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: MaskedL1Loss
    loss_weight: 1.0
    reduction: mean

  #ssim_opt:
  #  type: SSIMLoss
  #  loss_weight: 0.1
  #  reduction: mean
  #gpt_opt:
  #  type: GradientPriorLoss
  #  loss_weight: 1e-3
  #  reduction: mean

  # aux_loss: true

# validation settings
val:
  val_freq: !!float 2500
  save_img: true
  pbar: true

  metrics:
    psnr_torch: # metric name, can be arbitrary
      type: calculate_psnr_torch
      crop_border: 2
      test_y_channel: false
    ssim_torch:
      type: calculate_ssim_torch
      crop_border: 2
      test_y_channel: false
    mask_ssim:
      type: calculate_region_ssim
      crop_border: 2
      test_y_channel: false
    mask_psnr:
      type: calculate_region_psnr
      crop_border: 2
      test_y_channel: false
    recognition:
      type: calculate_recognition
      crop_border: 2
      test_y_channel: false
    ned:
      type: calculate_recognition
      crop_border: 2
      test_y_channel: false
# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 2500
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
