# general settings
name: train_EPCNN_SRx4_pretrain
model_type: SRModel
scale: 4
num_gpu: auto
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: TFSR
    type: PairedImageDatasetTFSRwREC
    dataroot_gt: ["/data0_ssd2t/majianqi/TFSR", "/data0_ssd2t/majianqi/ReCTS", "/data0_ssd2t/majianqi/LSVT"]
    dataroot_lq: /data0_ssd2t/majianqi/TFSR
    meta_info_file: None
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 256
    use_hflip: true
    use_rot: false

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: TFSR
    type: PairedImageDatasetTFSRwREC
    dataroot_gt: /data0_ssd2t/majianqi/TFSR
    dataroot_lq: /data0_ssd2t/majianqi/TFSR
    io_backend:
      type: disk

# network structures
network_g:
  type: EPCNN
  scale: 4
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  up_kernel_size: 5
  pre_kernel_size: 3
  rgb_range: 1.
  RSB_scale: 0.1
# path
path:
  pretrain_network_g: ~
  strict_load_g: false
  resume_state: ~
  experiments_root: /data1_ssd4t/majianqi/experiments/train_EPCNN_SRx4_pretrain

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [150000, 200000, 300000, 475000]
    gamma: 0.5

  total_iter: 200000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: MaskedL1Loss
    loss_weight: 1.0
    reduction: mean


    #gpt_opt:
    #type: GradientPriorLoss
    #loss_weight: 1e-3
    #reduction: mean

  # aux_loss: false

# validation settings
val:
  val_freq: !!float 2e4
  save_img: true

  metrics:
    psnr_torch: # metric name, can be arbitrary
      type: calculate_psnr_torch
      crop_border: 2
      test_y_channel: false
    ssim_torch:
      type: calculate_ssim_torch
      crop_border: 2
      test_y_channel: false
    mask_ssim:
      type: calculate_region_ssim
      crop_border: 2
      test_y_channel: false
    mask_psnr:
      type: calculate_region_psnr
      crop_border: 2
      test_y_channel: false
    lpips:
      type: calculate_lpips
      crop_border: 2
      test_y_channel: false
    recognition:
      type: calculate_recognition
      crop_border: 2
      test_y_channel: false
    ned:
      type: calculate_recognition
      crop_border: 2
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 2e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
